spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: postmaster@sandboxc4406bef56e14681a8a8b6335f56341d.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false