spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&preferQueryMode=simple
    username: postgres.sijmyvkwilhvrwgnhzpa
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: postmaster@sandboxc4406bef56e14681a8a8b6335f56341d.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
  web-socket:
    allowed-origin: "https://localhost:8080"

logging:
  level:
    com.dervlabs.chirp: DEBUG